name: Docker PostGIS CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: postgis

jobs:

  build:
    strategy:
      matrix:
        postgres: [12, 13, 14, 15, 16, 17]
        postgis: ['3.5']

    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build/Push docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
      uses: docker/build-push-action@v4
      with:
        context: ./${{ env.VERSION }}/
        push: true
        tags: ghcr.io/iqgeo/docker-postgis/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        build-args: |
          IMAGE_TAG=${{ env.IMAGE_TAG }}
        platforms: linux/amd64,linux/arm64

    - name: Logout of GitHub Packages
      run: docker logout ghcr.io