name: Docker PostGIS CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: postgis

jobs:

  build:
    strategy:
      matrix:
        postgres: [12, 13, 14, 15, 16, 17]
        postgis: ['3.5']
        variant: ['default']


    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Context Path
      id: set-context
      run: |
        if [ "${{ matrix.variant }}" = "default" ]; then
          echo "CONTEXT_PATH=./${{ env.VERSION }}/" >> $GITHUB_ENV
        else
          echo "CONTEXT_PATH=./${{ env.VERSION }}/${{ matrix.variant }}/" >> $GITHUB_ENV
        fi

    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build/Push docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.CONTEXT_PATH }}
        push: true
        tags: ghcr.io/iqgeo/docker-postgis/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        build-args: |
          IMAGE_TAG=${{ env.IMAGE_TAG }}
        platforms: linux/amd64,linux/arm64

    - name: Logout of GitHub Packages
      run: docker logout ghcr.io